# FWS CONFIG

global:                                             # GLOBAL SETTINGS
    theme-name: 'FWS Starter _S'                    # set theme full name
    superadmin-emails:                              # superadmin can alter plugins/themes on server and receive fatal error emails
      - 'nick@forwardslashny.com'
      - 'miroslav@forwardslashny.com'
      - 'nenad@forwardslashny.com'
      - 'dusan@forwardslashny.com'
    allowed-localhosts:                             # list of allowed localhosts
      - '.local'
      - 'localhost/'
      - '.lndo.site'
    plugins-only-local-editing: true                # prevent add/update/delete of plugins/themes on non-localhosts, except for superadmins
    cf7-custom-templates: true                     # enable/disable custom HTML and MJML templates for cf7 plugin
    acf-only-local-editing: true                    # acf only possible to edit and manage on local environment

acf-options-page:                                   # DEFINE ACF OPTIONS PAGES
    enable: true                                    # enable/disable options top level page
    subpages: ['SVG Icons']                         # list of options sub pages

styleguide:                                         # DEFINE STYLEGUIDE
    pages:                                          # set list of all pages defining their titles and urls
        -
            title: 'FE Homepage'
            url: '/fe-homepage/'
    colors:                                         # set list of all colors, matching variables in scss file
        - 'black'
        - 'grey-light'
        - 'grey-mid'
        - 'grey'
        - 'grey-dark'
        - 'white'
        - 'red'
        - 'green'
        - 'blue'
    icons:                                          # set list of all svg icons
        - 'ico-arrow-up'
        - 'ico-arrow-down'
        - 'ico-arrow-left'
        - 'ico-arrow-right'
        - 'ico-happy'
        - 'ico-lock'
        - 'ico-plus-circle'
        - 'ico-user'
        - 'ico-dog'
    fonts:                                          # set list of all fonts, matching variables in scss file
        -
            name: 'Open Sans'
            class: 'font-main'
    titles:                                         # set list of all special titles defining their classes and dummy text
        -
            text: 'This is Page Title'
            class: 'page-title'
        -
            text: 'This is Section Title'
            class: 'section-title'
    buttons:                                        # set list of all buttons defining their classes and dummy text
        -
            text: 'Normal'
            class: 'btn'
        -
            text: 'Green Button'
            class: 'btn btn--green'
        -
            text: 'Big Button'
            class: 'btn btn--big'
        -
            text: 'Big Green Button'
            class: 'btn btn--big btn--green'
