# FWS CONFIG

global:                                             # GLOBAL SETTINGS
    theme-name: 'FWS Starter _S'                    # set theme full name
    recovery-mode-emails:                           # change the fatal error handler email address from admin's to our internal
        - 'nick@forwardslashny.com'
        - 'boris@forwardslashny.com'
        - 'petar@forwardslashny.com'
        - 'dusan@forwardslashny.com'
    prevent-plugin-update:                          # only users logged in with declared email domain are allowed to add/update/remove plugins
        enable: true                                # enable/disable this rule
        domain: forwardslashny.com                  # allowed email domain
    cf7-custom-templates: true                      # enable/disable custom HTML and MJML templates for cf7 plugin
    acf-only-local-editing:                         # acf only possible to edit and manage on local environment
        enable: true                                # enable/disable this rule
        allowed-hosts:                              # list of allowed hosts
            - '.local'
            - 'localhost/'
            - '.lndo.site'

acf-options-page:                                   # DEFINE ACF OPTIONS PAGES
    enable: true                                    # enable/disable options top level page
    subpages: ['SVG Icons']                         # list of options sub pages

acf-flexible-content:                               # DEFINE ACF FLEXIBLE CONTENT GROUPS AND FIELDS
    default-page-template:                          # define flexible content for default page template
        autoload: true                              # set whether or not to autoload this flexible content group
        field-name: 'Content'                       # filed name that will show on page
        location:                                   # set location where this field group will load
            param: 'page_template'
            value: 'default'
        hide-on-screen: [ 'the_content' ]           # set rules for default meta fields that should be hidden on a page
        layouts:                                    # set flex content layouts/blocks that will show for this group
            -
                title: 'Banner'
                group_id: 'group_5d70e7dfa2562'
            -
                title: 'Basic Block'
                group_id: 'group_5d70e7ea08bce'
            -
                title: 'Slider'
                group_id: 'group_5d70e7f775076'
            -
                title: 'Vue Block'
                group_id: 'group_5dcd6b37b67a4'

styleguide:                                         # DEFINE STYLEGUIDE
    pages:                                          # set list of all pages defining their titles and urls
        -
            title: 'FE Homepage'
            url: '/fe-homepage/'
    colors:
        mine-shaft: '#282828'
        sapphire: '#335099'
        dodger-blue: '#5C92FF'
        orange: '#F7931E'
        pattens-blue: '#D4E5FF'
        mystic: '#E1E6EE'
        watusi: '#FFE8D2'
        pot-pourri: '#FCF5EE'
        pearl-bush: '#EFE8E2'
    icons:                                          # set list of all svg icons
        - 'ico-eye-slash-regular'
        - 'ico-eye'
        - 'ico-paper'
        - 'ico-arrows'
        - 'ico-trash'
        - 'ico-pen'
        - 'ico-info'
        - 'ico-tabs'
        - 'ico-document'
        - 'ico-user'
        - 'ico-map'
        - 'ico-cards'
    fonts:                                          # set list of all fonts, matching variables in scss file
        -
            name: 'Proxima Nova'
            styles: 'Regular Bold'
        -
            name: 'Open Sans'
            styles: 'Regular Medium Semibold Bold'
        -
            name: 'Univia pro'
            styles: 'Vidaloka'
    buttons:                                        # set list of all buttons defining their classes and dummy text
        -
            text: 'Default'
            class: 'btn'
        -
            text: 'Default'
            class: 'btn btn--orange'
        -
            text: 'Default'
            class: 'btn btn--border'
        -
            text: 'Default'
            class: 'btn btn--sm btn--blue'
        -
            icon: ['ico-gps', 'btn-icon']
            class: 'btn btn--icon'
