# FWS CONFIG

global:                                             # GLOBAL SETTINGS
    theme-name: 'FWS Starter _S'                    # set theme full name
    superadmin-emails:                              # superadmin can alter plugins/themes on server and receive fatal error emails
      - 'nick@forwardslashny.com'
      - 'miroslav@forwardslashny.com'
      - 'nenad@forwardslashny.com'
      - 'dusan@forwardslashny.com'
    allowed-localhosts:                             # list of allowed localhosts
      - '.local'
      - 'localhost/'
      - '.lndo.site'
    plugins-only-local-editing: true                # prevent add/update/delete of plugins/themes on non-localhosts, except for superadmins
    cf7-custom-templates: false                     # enable/disable custom HTML and MJML templates for cf7 plugin
    acf-only-local-editing: true                    # acf only possible to edit and manage on local environment
    clickjacking-protection: true                   # prevent clickjacking by opening site through iframe

acf-options-page:                                   # DEFINE ACF OPTIONS PAGES
    enable: true                                    # enable/disable options top level page
    subpages: ['SVG Icons']                         # list of options sub pages

styleguide:                                         # DEFINE STYLEGUIDE
    pages:                                          # set list of all pages defining their titles and urls
        -
            title: 'FE Homepage'
            url: '/fe-homepage/'
    colors:
        mine-shaft: '#282828'
        sapphire: '#335099'
        dodger-blue: '#5C92FF'
        orange: '#F7931E'
        pattens-blue: '#D4E5FF'
        mystic: '#E1E6EE'
        watusi: '#FFE8D2'
        pot-pourri: '#FCF5EE'
        pearl-bush: '#EFE8E2'
    icons:                                          # set list of all svg icons
        - 'ico-eye-slash-regular'
        - 'ico-eye'
        - 'ico-paper'
        - 'ico-arrows'
        - 'ico-trash'
        - 'ico-pen'
        - 'ico-info'
        - 'ico-tabs'
        - 'ico-document'
        - 'ico-user'
        - 'ico-maps'
        - 'ico-cards'
    fonts:                                          # set list of all fonts, matching variables in scss file
        -
            name: 'Proxima Nova'
            styles: 'Regular Bold'
        -
            name: 'Open Sans'
            styles: 'Regular Medium Semibold Bold'
        -
            name: 'Univia pro'
            styles: 'Vidaloka'
    buttons:                                        # set list of all buttons defining their classes and dummy text
        -
            text: 'Default'
            class: 'btn'
        -
            text: 'Default'
            class: 'btn btn--orange'
        -
            text: 'Default'
            class: 'btn btn--border'
        -
            text: 'Default'
            class: 'btn btn--sm btn--blue'
        -
            icon: ['ico-gps', 'btn-icon']
            class: 'btn btn--icon'
