<!--Do NOT change this file manually, it is being generated by svgicons script.-->

<template>
    <component v-bind:is="component"/>
</template>

<script>
    import startcase from 'lodash.startcase';
	import Happy from '../../../../assets/svg/ico-happy.svg';

    export default {
        props: {
            iconName: {
                type: String,
                required: true
            }
        },
        components: {
			Happy
        },
        computed: {
            component() {
                return startcase(this.iconName.replace('ico-', '')).replace(' ', '');
            }
        }
    };
</script>
