<!--Do NOT change this file manually, it is being generated by svgicons script.-->

<template>
    <component v-bind:is="component"/>
</template>

<script>
    import startcase from 'lodash.startcase';
    import ChevronDown from '../../../../assets/svg/ico-chevron-down.svg';
    import Dog from '../../../../assets/svg/ico-dog.svg';
    import Happy from '../../../../assets/svg/ico-happy.svg';
    import Lock from '../../../../assets/svg/ico-lock.svg';
    import PlusCircle from '../../../../assets/svg/ico-plus-circle.svg';
    import User from '../../../../assets/svg/ico-user.svg';

    export default {
        props: {
            iconName: {
                type: String,
                required: true
            }
        },
        components: {
            ChevronDown,
            Dog,
            Happy,
            Lock,
            PlusCircle,
            User,

        },
        computed: {
            component() {
                return startcase(this.iconName.replace('ico-', '')).replace(' ', '');
            }
        }
    };
</script>
